{application,test_add,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{test_add_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[test_add,test_add_app,test_add_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
